# -*- coding: utf-8 -*-
"""testecrimesp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lawA284SB0y90Hs7PLND9x-MamOL9ddJ
"""

import logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s', force=True)
logging.info("This log message will now appear in Colab.")

logging.basicConfig(filename='resultados.log', level=logging.DEBUG, force=True)

import pandas as pd
import numpy as np
import seaborn as sns
import unidecode as unidecode
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.feature_selection import SelectKBest
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier

df1 = pd.read_csv("JAN_JUN_2025.csv", encoding='utf-8', sep=';')
df2 = pd.read_csv("JUL_DEZ_2025.csv", encoding='utf-8', sep=';')
full_df = pd.concat([df1, df2], ignore_index=True)
full_df.info()

# FERIADOS = [01/01, 25/01, 03/03, 04/03, 05/03, 01/04, 18/4, 20/4, 21/04, 01/05, 11/05, 12/06, 09/07, 10/08, 07/09, 12/10, 15/10, 17/10,
# 28/10, 02/11, 15/11, 20/11, 25/12]
feriados_sp = {
    (1,1),   # Ano novo
    (3,3),   # Carnaval
    (3,4),   # Carnaval
    (3,5),   # CarnavaL
    (4,18),  # Sexta-feira santa
    (4,20),  # Páscoa
    (4,21),  # Tiradentes
    (5,1),   # Dia do trabalho
    (5,11),  # Dia das mães
    (6,12),  # Dia dos namorados
    (6,19),  # Corpus Chisti
    (7,9),   # Revolução Constitucionalista
    (8,10),  # Dia dos pais
    (9,7),   # Independência do Brasil
    (10,12), # Nossa Senhora Aparecida
    (10,15), # Dia do Professor
    (10,17), # Dia do Comércio
    (10,28), # Dia do Servidor Público
    (11,2),  # Finados
    (11,15), # Proclamação da República
    (11,20), # Consciência Negra
    (12,25), # Natal
  }

df_remove_features = full_df.drop(columns=["ANO_BO","NOME_DEPARTAMENTO", "NOME_SECCIONAL", "NOME_DELEGACIA", "NUM_BO", \
                      "DATA_REGISTRO", "DESCR_SUBTIPOLOCAL", "LOGRADOURO","NUMERO_LOGRADOURO", "LATITUDE", "LONGITUDE",
                      "NOME_DELEGACIA_CIRCUNSCRICAO", "NOME_DEPARTAMENTO_CIRCUNSCRICAO", "NOME_SECCIONAL_CIRCUNSCRICAO",
                      "NOME_MUNICIPIO_CIRCUNSCRICAO", "DESCR_CONDUTA", "NATUREZA_APURADA", "MES_ESTATISTICA",
                      "ANO_ESTATISTICA", "CMD", "BTL", "CIA"])
df_remove_features.info()

# TRANSFORMA DADOS DAS LINHAS DE MAIÚSCULOS PARA MINÚSCULOS
df_lowercase = df_remove_features.apply(lambda x: x.str.lower())

# REMOVE PONTUAÇÃO DE STRINGS
columns_clean = ['NOME_MUNICIPIO', 'DESC_PERIODO','BAIRRO', 'DESCR_TIPOLOCAL', 'RUBRICA']
for col in columns_clean:
    df_lowercase[col] = df_lowercase[col].map(lambda x: unidecode.unidecode(x) if isinstance(x, str) else x)

print(df_lowercase.iloc[1851])

df_lowercase[df_lowercase['DATA_OCORRENCIA_BO'].eq('14º d.p. pinheiros')]

# ADIÇÃO DE FEATURES: DIA, MES, ANO
df_lowercase['DATA_OCORRENCIA_BO'] = pd.to_datetime(df_lowercase['DATA_OCORRENCIA_BO'], dayfirst=True)
df_lowercase['ANO'] = pd.to_datetime(df_lowercase['DATA_OCORRENCIA_BO']).dt.year.astype('Int64')
df_lowercase['MES'] = pd.to_datetime(df_lowercase['DATA_OCORRENCIA_BO']).dt.month.astype('Int64')
df_lowercase['DIA'] = pd.to_datetime(df_lowercase['DATA_OCORRENCIA_BO']).dt.day.astype('Int64')
df_lowercase['DIA_SEM'] = df_lowercase['DATA_OCORRENCIA_BO'].dt.day_name()
df_lowercase['FERIADO'] = False

df_lowercase['DIA_SEM'] = df_lowercase['DIA_SEM'].str.lower()

# REMOÇÃO DE LINHAS EM QUE AMBAS AS FEATURES SÃO 'NULL'
df_rem = df_lowercase.dropna(subset=["DESC_PERIODO", "HORA_OCORRENCIA_BO"], how='all')
df_rem1 = df_rem.drop(columns=['DATA_OCORRENCIA_BO'])

# REMOÇÃO DE NULOS
df_rem2 = df_rem1.dropna(subset=['DESCR_TIPOLOCAL', 'BAIRRO', 'RUBRICA', 'ANO', 'MES', 'DIA_SEM', 'DIA'])

# REMOÇÃO DE LINHAS COM DADOS INÚTEIS E/OU CONFLITANTES
df_rem3 = df_rem2[df_rem2['DESC_PERIODO'] != "em hora incerta"]
df_rem4 = df_rem3[df_rem3['ANO'] == 2025]

# USANDO BOOLEAN MASK PARA MODIFICAR LINHAS VÁLIDAS PORÈM COM VALORES FORA DO PADRÃO
mask1 = df_rem4['HORA_OCORRENCIA_BO'].str.contains(r'.', na=False)
df_rem4.loc[mask1]

# MASKS BOOLEANOS PREENCHEM OS VALORES FALTANTES DA COLUNA 'DESC_PERIODO' COM BASE EM 'HORA_OCORRENCIA_BO'
mask1 = df_rem4['HORA_OCORRENCIA_BO'].between('06:00:00', '11:59:59')
df_rem4.loc[mask1, 'DESC_PERIODO'] = "pela manha"

mask2 = df_rem4['HORA_OCORRENCIA_BO'].between('12:00:00', '17:59:59')
df_rem4.loc[mask2, 'DESC_PERIODO'] = "a tarde"

mask3 = df_rem4['HORA_OCORRENCIA_BO'].between('18:00:00', '23:59:59')
df_rem4.loc[mask3, 'DESC_PERIODO'] = "a noite"

mask4 = df_rem4['HORA_OCORRENCIA_BO'].between("00:00:00", "05:59:59")
df_rem4.loc[mask4, 'DESC_PERIODO'] = "de madrugada"

# A FEATURE 'DIA' PRECISA SER UMA STRING DO DIA DA SEMANA E NÃO NUMÉRICO, ASSOCIAR CADA MÊS A UM ARRAY/BIBLIOTECA? COMO FAZER COM OS FERIADOS PARA NÃO FAZER 1 POR 1?
def feriado(dia, mes):
  return (mes, dia) in feriados_sp

df_rem4['FERIADO'] = df_rem4.apply(lambda row: feriado(row['DIA'], row['MES']), axis = 1)

def print_missing(df):
  print(df.isna().sum() * 100 / len(df))

print_missing(df_rem4)

hora = pd.to_datetime(df_rem4['HORA_OCORRENCIA_BO'], format='%H:%M:%S', errors='coerce')

df_rem4['HORA_OCORRENCIA_ADAPTADA'] = (hora.dt.floor('30min').dt.strftime('%H:%M'))

df_rem4['HORA_OCORRENCIA_ADAPTADA'] = df_rem4['HORA_OCORRENCIA_ADAPTADA'].fillna("Desconhecido")
df_rem5 = df_rem4.drop(columns=['HORA_OCORRENCIA_BO', 'DIA'])

df_rem4['NOME_MUNICIPIO'].value_counts()

"""# Registro"""

df_registro = df_rem4
df_registro = df_registro[df_registro['NOME_MUNICIPIO'] == 'registro'].copy()
print(df_registro['DESC_PERIODO'].value_counts())

df_registro = df_rem4
df_registro = df_registro[df_registro['NOME_MUNICIPIO'] == 'registro'].copy()

features_registro = [ 'MES', 'DIA_SEM', 'FERIADO', 'BAIRRO', 'RUBRICA', 'DESCR_TIPOLOCAL']
X = df_registro[features_registro]
y = df_registro['DESC_PERIODO']
categorical_cols_registro = [ 'DIA_SEM', 'BAIRRO', 'RUBRICA', 'DESCR_TIPOLOCAL']

X = pd.get_dummies(X, columns=categorical_cols_registro)

train_mask = df_registro['MES'] <= 9

Xtrain = X[train_mask]
Xtest = X[train_mask]
ytrain = y[train_mask]
ytest_re = y[train_mask]

label = LabelEncoder()

ytrain = label.fit_transform(ytrain)
ytest_re = label.transform(ytest_re)

scaler = StandardScaler()

Xtrain_scaled = scaler.fit_transform(Xtrain)
Xtest_scaled = scaler.transform(Xtest)

knn = KNeighborsClassifier(n_neighbors=33, weights='distance', algorithm='auto')
knn.fit(Xtrain_scaled, ytest_re)
ypred_re_knn = knn.predict(Xtest_scaled)

print(classification_report(ytest_re, ypred_re_knn, target_names=label.classes_, zero_division=0))

disp = ConfusionMatrixDisplay.from_predictions(ytest_re, ypred_re_knn, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Registro - KNN")
plt.show()

dt = DecisionTreeClassifier(max_depth=20, min_samples_leaf=5, random_state=42, class_weight='balanced')
dt.fit(Xtrain, ytrain)
ypred_re_dt = dt.predict(Xtest)

print(classification_report(ytest_re, ypred_re_dt, target_names=label.classes_, zero_division=0))

disp = ConfusionMatrixDisplay.from_predictions(ytest_re, ypred_re_dt, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Registro - DT")
plt.show()

rf = RandomForestClassifier(n_estimators=100, min_samples_leaf=5, random_state=42, class_weight='balanced')
rf.fit(Xtrain, ytrain)

ypred_re_rf = rf.predict(Xtest)

print(classification_report(ytest_re, ypred_re_rf, target_names=label.classes_))

disp = ConfusionMatrixDisplay.from_predictions(ytest_re, ypred_re_rf, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Registro - Random Forest")
plt.show()

CBC = GradientBoostingClassifier(n_estimators=50, learning_rate=0.5, max_depth=5, min_samples_leaf=10, subsample=0.8, random_state=42)
CBC.fit(Xtrain, ytrain)

ypred_re_cbc = CBC.predict(Xtest)

print(classification_report(ytest_re, ypred_re_cbc, target_names=label.classes_))

disp = ConfusionMatrixDisplay.from_predictions(ytest_re, ypred_re_cbc, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Registro - GradientBoostClassifier")
plt.show()

"""# Ribeirão Preto"""

df_ribeirao = df_rem4
df_ribeirao = df_ribeirao[df_ribeirao['NOME_MUNICIPIO'] == 'ribeirao preto'].copy()
print(df_ribeirao['DESC_PERIODO'].value_counts)

df_ribeirao = df_rem4
df_ribeirao = df_ribeirao[df_ribeirao['NOME_MUNICIPIO'] == 'ribeirao preto'].copy()

features_ribeirao = ['MES', 'DIA_SEM', 'FERIADO', 'BAIRRO', 'RUBRICA', 'DESCR_TIPOLOCAL']
X = df_ribeirao[features_ribeirao]
y = df_ribeirao['DESC_PERIODO']
categorical_cols_ribeirao = ['DIA_SEM', 'BAIRRO', 'RUBRICA', 'DESCR_TIPOLOCAL']

X = pd.get_dummies(X, columns=categorical_cols_ribeirao)

train_mask = df_ribeirao['MES'] <= 9

Xtrain = X[train_mask]
Xtest = X[train_mask]
ytrain = y[train_mask]
ytest_ri = y[train_mask]

label = LabelEncoder()

ytrain = label.fit_transform(ytrain)
ytest_ri = label.transform(ytest_ri)

dt = DecisionTreeClassifier(max_depth=20, min_samples_leaf=5, random_state=42, class_weight='balanced')
dt.fit(Xtrain, ytrain)

ypred_ri_dt = dt.predict(Xtest)

print(classification_report(ytest_ri, ypred_ri_dt, target_names=label.classes_))

disp = ConfusionMatrixDisplay.from_predictions(ytest_ri, ypred_ri_dt, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Ribeirão Preto - Decison Tree")
plt.show()

scaler = StandardScaler()

Xtrain_scaled = scaler.fit_transform(Xtrain)
Xtest_scaled = scaler.transform(Xtest)

knn = KNeighborsClassifier(n_neighbors=33, weights='distance', algorithm='auto')
knn.fit(Xtrain_scaled, ytest_ri)
ypred_ri_knn = knn.predict(Xtest_scaled)

print(classification_report(ytest_ri, ypred_ri_knn, target_names=label.classes_, zero_division=0))

disp = ConfusionMatrixDisplay.from_predictions(ytest_ri, ypred_ri_knn, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Ribeirão Preto - KNN")
plt.show()

rf = RandomForestClassifier(n_estimators=100, min_samples_leaf=5, random_state=42, class_weight='balanced')
rf.fit(Xtrain, ytrain)

ypred_ri_rf = rf.predict(Xtest)

print(classification_report(ytest_ri, ypred_ri_rf, target_names=label.classes_))

disp = ConfusionMatrixDisplay.from_predictions(ytest_ri, ypred_ri_rf, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Ribeirão Preto - Random Forest")
plt.show()

CBC = GradientBoostingClassifier(n_estimators=20, learning_rate=0.5, max_depth=5, min_samples_leaf=10, subsample=0.8, random_state=42)
CBC.fit(Xtrain, ytrain)

ypred_ri_cbc = CBC.predict(Xtest)

print(classification_report(ytest_ri, ypred_ri_cbc, target_names=label.classes_))

disp = ConfusionMatrixDisplay.from_predictions(ytest_ri, ypred_ri_cbc, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Ribeirão Preto - GradientBoostClassifier")
plt.show()

"""# Campinas"""

df_campinas = df_rem4
df_campinas = df_campinas[df_campinas['NOME_MUNICIPIO'] == 'campinas'].copy()
print(df_campinas['DESC_PERIODO'].value_counts())

df_campinas = df_rem4
df_campinas = df_campinas[df_campinas['NOME_MUNICIPIO'] == 'campinas'].copy()

features_campinas = ['MES', 'DIA_SEM', 'FERIADO', 'BAIRRO', 'RUBRICA', 'DESCR_TIPOLOCAL']
X = df_campinas[features_campinas]
y = df_campinas['DESC_PERIODO']
categorical_cols_campinas = ['DIA_SEM', 'BAIRRO', 'RUBRICA', 'DESCR_TIPOLOCAL']

X = pd.get_dummies(X, categorical_cols_campinas)

train_mask = df_campinas['MES'] <= 9

Xtrain = X[train_mask]
Xtest = X[train_mask]
ytrain = y[train_mask]
ytest_ca = y[train_mask]

label = LabelEncoder()

ytrain = label.fit_transform(ytrain)
ytest_ca = label.transform(ytest_ca)

rf = RandomForestClassifier(n_estimators=100, min_samples_leaf=5, random_state=42, class_weight='balanced')
rf.fit(Xtrain, ytrain)

ypred_ca = rf.predict(Xtest)

print(classification_report(ytest_ca, ypred_ca, target_names=label.classes_))

disp = ConfusionMatrixDisplay.from_predictions(ytest_ca, ypred_ca, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Campinas - Random Forest")
plt.show()

scaler = StandardScaler()

Xtrain_scaled = scaler.fit_transform(Xtrain)
Xtest_scaled = scaler.transform(Xtest)

knn = KNeighborsClassifier(n_neighbors=33, weights='distance', algorithm='auto')
knn.fit(Xtrain_scaled, ytest_ca)
ypred_ca_knn = knn.predict(Xtest_scaled)

print(classification_report(ytest_ca, ypred_ca_knn, target_names=label.classes_, zero_division=0))

disp = ConfusionMatrixDisplay.from_predictions(ytest_ca, ypred_ca_knn, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Campinas - KNN")
plt.show()

dt = DecisionTreeClassifier(max_depth=20, min_samples_leaf=5, random_state=42, class_weight='balanced')
dt.fit(Xtrain, ytrain)
ypred_ca_dt = dt.predict(Xtest)

print(classification_report(ytest_ca, ypred_ca_dt, target_names=label.classes_, zero_division=0))

disp = ConfusionMatrixDisplay.from_predictions(ytest_ca, ypred_ca_dt, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Campinas - DT")
plt.show()

CBC = GradientBoostingClassifier(n_estimators=20, learning_rate=0.5, max_depth=5, min_samples_leaf=10, subsample=0.8, random_state=42)
CBC.fit(Xtrain, ytrain)

ypred_ca_cbc = CBC.predict(Xtest)

print(classification_report(ytest_ca, ypred_ca_cbc, target_names=label.classes_))

disp = ConfusionMatrixDisplay.from_predictions(ytest_ca, ypred_ca_cbc, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("Campinas - GradientBoostClassifier")
plt.show()

"""# São Paulo capital

"""

# https://www.datacamp.com/tutorial/guide-to-the-gradient-boosting-algorithm

df_sp = df_rem4
df_sp = df_sp[df_sp['NOME_MUNICIPIO'] == 's.paulo'].copy()
print(df_sp['DESC_PERIODO'].value_counts())

df_sp = df_rem4
df_sp = df_sp[df_sp['NOME_MUNICIPIO'] == 's.paulo'].copy()

features_sp = ['MES', 'DIA_SEM', 'FERIADO', 'BAIRRO', 'RUBRICA']
X = df_sp[features_sp]
y = df_sp['DESC_PERIODO']
categorical_cols_sp = ['DIA_SEM', 'BAIRRO', 'RUBRICA']

X = pd.get_dummies(X, categorical_cols_sp)

train_mask = df_sp['MES'] <= 9

Xtrain = X[train_mask]
Xtest = X[train_mask]
ytrain = y[train_mask]
ytest_sp = y[train_mask]

label = LabelEncoder()

ytrain = label.fit_transform(ytrain)
ytest_sp = label.transform(ytest_sp)

# reduzir n_estimators
CBC = GradientBoostingClassifier(n_estimators=50, learning_rate=0.5, max_depth=5, min_samples_leaf=10, subsample=0.8, random_state=42)
CBC.fit(Xtrain, ytrain)

ypred_sp = CBC.predict(Xtest)

print(classification_report(ytest_sp, ypred_sp, target_names=label.classes_))

disp = ConfusionMatrixDisplay.from_predictions(ytest_sp, ypred_sp, display_labels=label.classes_, xticks_rotation=45)
disp.ax_.set_title("São Paulo - GradientBoostClassifier")
plt.show()

"""# São Paulo e Região Metropolitana

"""

print(df_rem4['DESC_PERIODO'].value_counts())
